/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: activity_tracking.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "activity_tracking.pb-c.h"
void   root_container__init
                     (RootContainer         *message)
{
  static const RootContainer init_value = ROOT_CONTAINER__INIT;
  *message = init_value;
}
size_t root_container__get_packed_size
                     (const RootContainer *message)
{
  assert(message->base.descriptor == &root_container__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t root_container__pack
                     (const RootContainer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &root_container__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t root_container__pack_to_buffer
                     (const RootContainer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &root_container__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RootContainer *
       root_container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RootContainer *)
     protobuf_c_message_unpack (&root_container__descriptor,
                                allocator, len, data);
}
void   root_container__free_unpacked
                     (RootContainer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &root_container__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   metadata__init
                     (Metadata         *message)
{
  static const Metadata init_value = METADATA__INIT;
  *message = init_value;
}
size_t metadata__get_packed_size
                     (const Metadata *message)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t metadata__pack
                     (const Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t metadata__pack_to_buffer
                     (const Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Metadata *
       metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Metadata *)
     protobuf_c_message_unpack (&metadata__descriptor,
                                allocator, len, data);
}
void   metadata__free_unpacked
                     (Metadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_container__init
                     (DataContainer         *message)
{
  static const DataContainer init_value = DATA_CONTAINER__INIT;
  *message = init_value;
}
size_t data_container__get_packed_size
                     (const DataContainer *message)
{
  assert(message->base.descriptor == &data_container__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_container__pack
                     (const DataContainer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_container__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_container__pack_to_buffer
                     (const DataContainer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_container__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataContainer *
       data_container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataContainer *)
     protobuf_c_message_unpack (&data_container__descriptor,
                                allocator, len, data);
}
void   data_container__free_unpacked
                     (DataContainer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_container__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sub_data_container__init
                     (SubDataContainer         *message)
{
  static const SubDataContainer init_value = SUB_DATA_CONTAINER__INIT;
  *message = init_value;
}
size_t sub_data_container__get_packed_size
                     (const SubDataContainer *message)
{
  assert(message->base.descriptor == &sub_data_container__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sub_data_container__pack
                     (const SubDataContainer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sub_data_container__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sub_data_container__pack_to_buffer
                     (const SubDataContainer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sub_data_container__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SubDataContainer *
       sub_data_container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SubDataContainer *)
     protobuf_c_message_unpack (&sub_data_container__descriptor,
                                allocator, len, data);
}
void   sub_data_container__free_unpacked
                     (SubDataContainer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sub_data_container__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_info__init
                     (DeviceInfo         *message)
{
  static const DeviceInfo init_value = DEVICE_INFO__INIT;
  *message = init_value;
}
size_t device_info__get_packed_size
                     (const DeviceInfo *message)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_info__pack
                     (const DeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_info__pack_to_buffer
                     (const DeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInfo *
       device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInfo *)
     protobuf_c_message_unpack (&device_info__descriptor,
                                allocator, len, data);
}
void   device_info__free_unpacked
                     (DeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   software_version__init
                     (SoftwareVersion         *message)
{
  static const SoftwareVersion init_value = SOFTWARE_VERSION__INIT;
  *message = init_value;
}
size_t software_version__get_packed_size
                     (const SoftwareVersion *message)
{
  assert(message->base.descriptor == &software_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t software_version__pack
                     (const SoftwareVersion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &software_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t software_version__pack_to_buffer
                     (const SoftwareVersion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &software_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SoftwareVersion *
       software_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SoftwareVersion *)
     protobuf_c_message_unpack (&software_version__descriptor,
                                allocator, len, data);
}
void   software_version__free_unpacked
                     (SoftwareVersion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &software_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unknown01__init
                     (Unknown01         *message)
{
  static const Unknown01 init_value = UNKNOWN01__INIT;
  *message = init_value;
}
size_t unknown01__get_packed_size
                     (const Unknown01 *message)
{
  assert(message->base.descriptor == &unknown01__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unknown01__pack
                     (const Unknown01 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unknown01__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unknown01__pack_to_buffer
                     (const Unknown01 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unknown01__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Unknown01 *
       unknown01__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Unknown01 *)
     protobuf_c_message_unpack (&unknown01__descriptor,
                                allocator, len, data);
}
void   unknown01__free_unpacked
                     (Unknown01 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unknown01__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   summary_record__init
                     (SummaryRecord         *message)
{
  static const SummaryRecord init_value = SUMMARY_RECORD__INIT;
  *message = init_value;
}
size_t summary_record__get_packed_size
                     (const SummaryRecord *message)
{
  assert(message->base.descriptor == &summary_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t summary_record__pack
                     (const SummaryRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &summary_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t summary_record__pack_to_buffer
                     (const SummaryRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &summary_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SummaryRecord *
       summary_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SummaryRecord *)
     protobuf_c_message_unpack (&summary_record__descriptor,
                                allocator, len, data);
}
void   summary_record__free_unpacked
                     (SummaryRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &summary_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   record2__init
                     (Record2         *message)
{
  static const Record2 init_value = RECORD2__INIT;
  *message = init_value;
}
size_t record2__get_packed_size
                     (const Record2 *message)
{
  assert(message->base.descriptor == &record2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t record2__pack
                     (const Record2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &record2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t record2__pack_to_buffer
                     (const Record2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &record2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Record2 *
       record2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Record2 *)
     protobuf_c_message_unpack (&record2__descriptor,
                                allocator, len, data);
}
void   record2__free_unpacked
                     (Record2 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &record2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tag_value_container__init
                     (TagValueContainer         *message)
{
  static const TagValueContainer init_value = TAG_VALUE_CONTAINER__INIT;
  *message = init_value;
}
size_t tag_value_container__get_packed_size
                     (const TagValueContainer *message)
{
  assert(message->base.descriptor == &tag_value_container__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tag_value_container__pack
                     (const TagValueContainer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tag_value_container__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tag_value_container__pack_to_buffer
                     (const TagValueContainer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tag_value_container__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TagValueContainer *
       tag_value_container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TagValueContainer *)
     protobuf_c_message_unpack (&tag_value_container__descriptor,
                                allocator, len, data);
}
void   tag_value_container__free_unpacked
                     (TagValueContainer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tag_value_container__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value_container__init
                     (ValueContainer         *message)
{
  static const ValueContainer init_value = VALUE_CONTAINER__INIT;
  *message = init_value;
}
size_t value_container__get_packed_size
                     (const ValueContainer *message)
{
  assert(message->base.descriptor == &value_container__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value_container__pack
                     (const ValueContainer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &value_container__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value_container__pack_to_buffer
                     (const ValueContainer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &value_container__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ValueContainer *
       value_container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ValueContainer *)
     protobuf_c_message_unpack (&value_container__descriptor,
                                allocator, len, data);
}
void   value_container__free_unpacked
                     (ValueContainer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &value_container__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   record3__init
                     (Record3         *message)
{
  static const Record3 init_value = RECORD3__INIT;
  *message = init_value;
}
size_t record3__get_packed_size
                     (const Record3 *message)
{
  assert(message->base.descriptor == &record3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t record3__pack
                     (const Record3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &record3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t record3__pack_to_buffer
                     (const Record3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &record3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Record3 *
       record3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Record3 *)
     protobuf_c_message_unpack (&record3__descriptor,
                                allocator, len, data);
}
void   record3__free_unpacked
                     (Record3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &record3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   record4__init
                     (Record4         *message)
{
  static const Record4 init_value = RECORD4__INIT;
  *message = init_value;
}
size_t record4__get_packed_size
                     (const Record4 *message)
{
  assert(message->base.descriptor == &record4__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t record4__pack
                     (const Record4 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &record4__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t record4__pack_to_buffer
                     (const Record4 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &record4__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Record4 *
       record4__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Record4 *)
     protobuf_c_message_unpack (&record4__descriptor,
                                allocator, len, data);
}
void   record4__free_unpacked
                     (Record4 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &record4__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   activity__init
                     (Activity         *message)
{
  static const Activity init_value = ACTIVITY__INIT;
  *message = init_value;
}
size_t activity__get_packed_size
                     (const Activity *message)
{
  assert(message->base.descriptor == &activity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t activity__pack
                     (const Activity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &activity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t activity__pack_to_buffer
                     (const Activity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &activity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Activity *
       activity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Activity *)
     protobuf_c_message_unpack (&activity__descriptor,
                                allocator, len, data);
}
void   activity__free_unpacked
                     (Activity *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &activity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor root_container__field_descriptors[2] =
{
  {
    "metadata",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RootContainer, metadata),
    &metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataContainer",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RootContainer, datacontainer),
    &data_container__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned root_container__field_indices_by_name[] = {
  1,   /* field[1] = dataContainer */
  0,   /* field[0] = metadata */
};
static const ProtobufCIntRange root_container__number_ranges[1 + 1] =
{
  { 7, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor root_container__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RootContainer",
  "RootContainer",
  "RootContainer",
  "",
  sizeof(RootContainer),
  2,
  root_container__field_descriptors,
  root_container__field_indices_by_name,
  1,  root_container__number_ranges,
  (ProtobufCMessageInit) root_container__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor metadata__field_descriptors[2] =
{
  {
    "unknown1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Metadata, unknown1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Metadata, unknown2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned metadata__field_indices_by_name[] = {
  0,   /* field[0] = unknown1 */
  1,   /* field[1] = unknown2 */
};
static const ProtobufCIntRange metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Metadata",
  "Metadata",
  "Metadata",
  "",
  sizeof(Metadata),
  2,
  metadata__field_descriptors,
  metadata__field_indices_by_name,
  1,  metadata__number_ranges,
  (ProtobufCMessageInit) metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_container__field_descriptors[1] =
{
  {
    "subDataContainer",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DataContainer, subdatacontainer),
    &sub_data_container__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_container__field_indices_by_name[] = {
  0,   /* field[0] = subDataContainer */
};
static const ProtobufCIntRange data_container__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data_container__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataContainer",
  "DataContainer",
  "DataContainer",
  "",
  sizeof(DataContainer),
  1,
  data_container__field_descriptors,
  data_container__field_indices_by_name,
  1,  data_container__number_ranges,
  (ProtobufCMessageInit) data_container__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sub_data_container__field_descriptors[5] =
{
  {
    "deviceInfo",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SubDataContainer, deviceinfo),
    &device_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "summary",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SubDataContainer, summary),
    &summary_record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "record2",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SubDataContainer, record2),
    &record2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "record3",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SubDataContainer, record3),
    &record3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "record4",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SubDataContainer, record4),
    &record4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sub_data_container__field_indices_by_name[] = {
  0,   /* field[0] = deviceInfo */
  2,   /* field[2] = record2 */
  3,   /* field[3] = record3 */
  4,   /* field[4] = record4 */
  1,   /* field[1] = summary */
};
static const ProtobufCIntRange sub_data_container__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sub_data_container__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SubDataContainer",
  "SubDataContainer",
  "SubDataContainer",
  "",
  sizeof(SubDataContainer),
  5,
  sub_data_container__field_descriptors,
  sub_data_container__field_indices_by_name,
  2,  sub_data_container__number_ranges,
  (ProtobufCMessageInit) sub_data_container__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_info__field_descriptors[3] =
{
  {
    "deviceName",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, devicename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "year",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "softwareVersion",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, softwareversion),
    &software_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_info__field_indices_by_name[] = {
  0,   /* field[0] = deviceName */
  2,   /* field[2] = softwareVersion */
  1,   /* field[1] = year */
};
static const ProtobufCIntRange device_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor device_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInfo",
  "DeviceInfo",
  "DeviceInfo",
  "",
  sizeof(DeviceInfo),
  3,
  device_info__field_descriptors,
  device_info__field_indices_by_name,
  1,  device_info__number_ranges,
  (ProtobufCMessageInit) device_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor software_version__field_descriptors[4] =
{
  {
    "majorVersion",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SoftwareVersion, majorversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mediumVersion",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SoftwareVersion, mediumversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minorVersion",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SoftwareVersion, minorversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown01",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SoftwareVersion, unknown01),
    &unknown01__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned software_version__field_indices_by_name[] = {
  0,   /* field[0] = majorVersion */
  1,   /* field[1] = mediumVersion */
  2,   /* field[2] = minorVersion */
  3,   /* field[3] = unknown01 */
};
static const ProtobufCIntRange software_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor software_version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SoftwareVersion",
  "SoftwareVersion",
  "SoftwareVersion",
  "",
  sizeof(SoftwareVersion),
  4,
  software_version__field_descriptors,
  software_version__field_indices_by_name,
  1,  software_version__number_ranges,
  (ProtobufCMessageInit) software_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unknown01__field_descriptors[1] =
{
  {
    "dummy",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Unknown01, has_dummy),
    offsetof(Unknown01, dummy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unknown01__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange unknown01__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor unknown01__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Unknown01",
  "Unknown01",
  "Unknown01",
  "",
  sizeof(Unknown01),
  1,
  unknown01__field_descriptors,
  unknown01__field_indices_by_name,
  1,  unknown01__number_ranges,
  (ProtobufCMessageInit) unknown01__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor summary_record__field_descriptors[11] =
{
  {
    "recordId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, recordid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeZone",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, timezone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steps",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, steps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activityTime",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, activitytime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "calories",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, calories),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baseCalories",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, basecalories),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown10",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SummaryRecord, has_unknown10),
    offsetof(SummaryRecord, unknown10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown11",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SummaryRecord, unknown11),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned summary_record__field_indices_by_name[] = {
  5,   /* field[5] = activityTime */
  8,   /* field[8] = baseCalories */
  7,   /* field[7] = calories */
  6,   /* field[6] = distance */
  3,   /* field[3] = interval */
  0,   /* field[0] = recordId */
  4,   /* field[4] = steps */
  1,   /* field[1] = time */
  2,   /* field[2] = timeZone */
  9,   /* field[9] = unknown10 */
  10,   /* field[10] = unknown11 */
};
static const ProtobufCIntRange summary_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor summary_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SummaryRecord",
  "SummaryRecord",
  "SummaryRecord",
  "",
  sizeof(SummaryRecord),
  11,
  summary_record__field_descriptors,
  summary_record__field_indices_by_name,
  1,  summary_record__number_ranges,
  (ProtobufCMessageInit) summary_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor record2__field_descriptors[6] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Record2, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record2, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tagValue",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Record2, n_tagvalue),
    offsetof(Record2, tagvalue),
    &tag_value_container__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown1",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record2, unknown1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown2",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record2, unknown2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown3",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record2, unknown3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned record2__field_indices_by_name[] = {
  1,   /* field[1] = interval */
  2,   /* field[2] = tagValue */
  0,   /* field[0] = time */
  3,   /* field[3] = unknown1 */
  4,   /* field[4] = unknown2 */
  5,   /* field[5] = unknown3 */
};
static const ProtobufCIntRange record2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor record2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Record2",
  "Record2",
  "Record2",
  "",
  sizeof(Record2),
  6,
  record2__field_descriptors,
  record2__field_indices_by_name,
  1,  record2__number_ranges,
  (ProtobufCMessageInit) record2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tag_value_container__field_descriptors[2] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TagValueContainer, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valueContainer",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TagValueContainer, valuecontainer),
    &value_container__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tag_value_container__field_indices_by_name[] = {
  0,   /* field[0] = tag */
  1,   /* field[1] = valueContainer */
};
static const ProtobufCIntRange tag_value_container__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tag_value_container__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TagValueContainer",
  "TagValueContainer",
  "TagValueContainer",
  "",
  sizeof(TagValueContainer),
  2,
  tag_value_container__field_descriptors,
  tag_value_container__field_indices_by_name,
  1,  tag_value_container__number_ranges,
  (ProtobufCMessageInit) tag_value_container__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value_container__field_descriptors[1] =
{
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ValueContainer, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value_container__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange value_container__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor value_container__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ValueContainer",
  "ValueContainer",
  "ValueContainer",
  "",
  sizeof(ValueContainer),
  1,
  value_container__field_descriptors,
  value_container__field_indices_by_name,
  1,  value_container__number_ranges,
  (ProtobufCMessageInit) value_container__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor record3__field_descriptors[5] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Record3, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record3, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartRate",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record3, heartrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value02",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record3, value02),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value03",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record3, value03),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned record3__field_indices_by_name[] = {
  2,   /* field[2] = heartRate */
  1,   /* field[1] = interval */
  0,   /* field[0] = time */
  3,   /* field[3] = value02 */
  4,   /* field[4] = value03 */
};
static const ProtobufCIntRange record3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor record3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Record3",
  "Record3",
  "Record3",
  "",
  sizeof(Record3),
  5,
  record3__field_descriptors,
  record3__field_indices_by_name,
  1,  record3__number_ranges,
  (ProtobufCMessageInit) record3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor record4__field_descriptors[3] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Record4, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Record4, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Record4, n_value),
    offsetof(Record4, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned record4__field_indices_by_name[] = {
  1,   /* field[1] = interval */
  0,   /* field[0] = time */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange record4__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor record4__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Record4",
  "Record4",
  "Record4",
  "",
  sizeof(Record4),
  3,
  record4__field_descriptors,
  record4__field_indices_by_name,
  1,  record4__number_ranges,
  (ProtobufCMessageInit) record4__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor activity__field_descriptors[1] =
{
  {
    "rootContainer",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Activity, n_rootcontainer),
    offsetof(Activity, rootcontainer),
    &root_container__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned activity__field_indices_by_name[] = {
  0,   /* field[0] = rootContainer */
};
static const ProtobufCIntRange activity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor activity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Activity",
  "Activity",
  "Activity",
  "",
  sizeof(Activity),
  1,
  activity__field_descriptors,
  activity__field_indices_by_name,
  1,  activity__number_ranges,
  (ProtobufCMessageInit) activity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
